name: Run Benchmarks

on:
  schedule:
    - cron: '0 0 * * 6'  # Run every Saturday
  workflow_dispatch:  # Allow manual triggering

jobs:
  run-benchmarks:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Update SSL certificates
      run: |
        sudo apt-get update
        sudo apt-get install -y ca-certificates
        sudo update-ca-certificates
        
    - name: Run benchmarks
      env:
        KAPPAML_API_KEY: ${{ secrets.KAPPAML_API_KEY }}
        # Add SSL verification environment variables
        REQUESTS_CA_BUNDLE: /etc/ssl/certs/ca-certificates.crt
        SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt
      run: python run_benchmarks.py
      
    - name: Upload benchmark results
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-results
        path: results/
        retention-days: 90 
        
    - name: Upload figures
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-figures
        path: figures/
        retention-days: 90 
